version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: inventory-fastapi-backend
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=8000
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: inventory-react-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

